# Generated by Django 4.1.1 on 2022-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stud_app", "0002_delete_prinipal_delete_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("employee_number", models.PositiveIntegerField()),
                ("course", models.CharField(max_length=100)),
            ],
        ),
    ]
